#!/bin/zsh

# Cool Agent Setup Script
# Author: Yuwei Liang

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the directory where this script is located
COOL_AGENT_DIR="$(cd "$(dirname "$0")" && pwd)"
SHELL_CONFIG="$HOME/.zshrc"

echo -e "${BLUE}Cool Agent Setup${NC}"
echo "=================="
echo ""

# Make bin scripts executable
echo -e "${YELLOW}Making scripts executable...${NC}"
chmod +x "$COOL_AGENT_DIR/bin/"*
chmod +x "$COOL_AGENT_DIR/aliases/aliases.sh"

# Check if already installed
if grep -q "Cool Agent CLI Aliases" "$SHELL_CONFIG" 2>/dev/null; then
    echo -e "${YELLOW}Cool Agent appears to already be installed.${NC}"
    echo -n "Would you like to reinstall? (y/N): "
    read response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}Setup cancelled.${NC}"
        exit 0
    fi
    
    # Remove existing installation
    echo -e "${YELLOW}Removing existing installation...${NC}"
    sed -i '' '/# Cool Agent CLI Aliases/,/# End Cool Agent CLI Aliases/d' "$SHELL_CONFIG"
fi

# Add to shell configuration
echo -e "${YELLOW}Adding Cool Agent to shell configuration...${NC}"

cat >> "$SHELL_CONFIG" << EOF

# Cool Agent CLI Aliases
# Auto-generated by setup.sh - Do not edit manually
if [[ -f "$COOL_AGENT_DIR/aliases/aliases.sh" ]]; then
    source "$COOL_AGENT_DIR/aliases/aliases.sh"
fi
# End Cool Agent CLI Aliases
EOF

echo -e "${GREEN}✓ Cool Agent installed successfully!${NC}"
echo ""
echo "Available commands:"
echo "  • ${BLUE}mrd${NC} or ${BLUE}downloads${NC} - Move recent downloads"
echo "  • ${BLUE}cool-help${NC} - Show all available commands"
echo "  • ${BLUE}cool-update${NC} - Reload aliases"
echo ""
echo -e "${YELLOW}To start using Cool Agent:${NC}"
echo "  1. Run: ${BLUE}source ~/.zshrc${NC}"
echo "  2. Or restart your terminal"
echo "  3. Type: ${BLUE}cool-help${NC}"
echo ""
echo -e "${GREEN}Happy coding! 🚀${NC}"